name: Release
on:
  - push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Default Java from the container is used.
      - run: ./gradlew javaVersion
        id: java-version

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest # TODO: use version from gradle.properties
          build-args: |
            JAVA=${{ steps.java-version.outputs.java-version }}

        # TODO: Make a release
