name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./src/test/resources/
        id: success
        with:
          file: src/test/resources/test.properties
          property: name
      - run: '[[ "Darth Vader" == "${{ steps.success.outputs.value }}" ]]'

      - uses: ./src/test/resources/
        id: default
        with:
          file: src/test/resources/unexisting.properties
          property: name
          default: Anakin Skywalker
      - run: '[[ "Anakin Skywalker" == "${{ steps.default.outputs.value }}" ]]'

      - uses: ./src/test/resources/
        id: failure
        with:
          file: src/test/resources/unexisting.properties
          property: name
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.failure.outcome }}" ]]'
